# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tune GitHub-hosted runner network
      uses: smorimoto/tune-github-hosted-runner-network@v1

    - name: Checkout tree
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build -v ./cmd/main.go

    - name: Test
      run: make test

    - name: Test for Data Race
      run: make test-race

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        directory: .
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: EchoVault/EchoVault

    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0

